version: 2

models:
  - name: transactions
    description: My transformation written in Python
    config:
      database: FS_DBT_DATABASE
      schema: FS_DBT_SCHEMA
      materialized: table
      tags: ['python']

  - name: customers
    description: My transformation written in Python
    config:
      database: FS_DBT_DATABASE
      schema: FS_DBT_SCHEMA
      materialized: table
      tags: ['python']

  - name: terminals
    description: My transformation written in Python
    config:
      database: FS_DBT_DATABASE
      schema: FS_DBT_SCHEMA
      materialized: table
      tags: ['python']